import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { FlatCompat } from '@eslint/eslintrc'
import { defineConfig, globalIgnores } from 'eslint/config'

const compat = new FlatCompat({
  baseDirectory: path.dirname(fileURLToPath(import.meta.url)),
})

export default defineConfig([
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  globalIgnores(['.next/**', 'node_modules/**', 'src/generated/**', 'outputs/**']),
  {
    rules: {
      // The project predates React Compiler linting. TypeScript remains the
      // source of truth for correctness while these components are migrated.
      '@typescript-eslint/no-explicit-any': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/refs': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },
  {
    files: ['functions/**/*.js'],
    rules: {
      // Catalyst Advanced I/O functions run as CommonJS entry points.
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  {
    files: ['next-env.d.ts'],
    rules: {
      // Generated by Next during production builds.
      '@typescript-eslint/triple-slash-reference': 'off',
    },
  },
])
